export {default as UserLogin} from './UserSignUpLogin/userLogin';
export {default as UserReg} from './UserSignUpLogin/userRegister';
export {default as Select} from './Selection/selecttion';
export {default as Header} from './Header/header';
export {default as ConLogin} from './ConsultantSignUpLogin/consultantLogin';
export {default as ConReg} from './ConsultantSignUpLogin/consultantRegister';
export {default as Splash} from './Splash/Splash';
export {default as UserDash} from './User/userDashboard';
export {default as Usertabs} from './User/tabs'
export {default as ConDash} from './Consultant/consultDashboard';
export {default as BMJS} from './User/bmjs';
